//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programming.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Languages
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "The LANGUAGE field is a required (DÝL alaný zorunludur).")]
        public string Language { get; set; }

        [StringLength(50,MinimumLength =4,ErrorMessage = "The FOUNDER field cannot be less than 4 characters or more than 50 characters. (KURUCU alaný 4 karakterden az, 50 karakterden fazla olamaz).")]
        [Required(ErrorMessage = "The FOUNDER field is a required (KURUCU alaný zorunludur).")]
        public string Founder { get; set; }

        [Range(typeof(DateTime),"1950-01-01", "2022-12-31", ErrorMessage = "The YEAR field must be between 1950 and 2022 (YIL alaný 1950 ile 2022 arasýnda olmalýdýr).")]
        [Required(ErrorMessage = "The YEAR field is a required (YIL alaný zorunludur).")]
        public System.DateTime Year { get; set; }

        [Required(ErrorMessage = "The ISPOPULAR field is a required.")]
        public bool IsPopular { get; set; }
    }
}
